#!/bin/awk -f

# Convert integers of a field representing a byte size to
# a human readable format
#
#
# Awk interface
#
# VARIABLES:
#
#	field (int)
#
#	blocksize (int) see du(1)
#

BEGIN {
	if (blocksize <= 0) {
		if (ENVIRON["BLOCK_SIZE"] > 0) {
			blocksize = ENVIRON["BLOCK_SIZE"]
		} else {
			blocksize = 1000
		}
	}

	if (length(field) == 0) {
		field = 1
	}

}

$field ~ /[0-9]+/ {
	$field = human($field,blocksize)
}

{
	print
}

function human(x,B) {
	split("kMGTEPYZ", unit, //)

	for (i in unit) {
		if (x < B)
			break

		x /= B
	}

	return sprintf("%.2f%s", x, unit[i])
}
