#!/bin/sh

PROGRAM_NAME="fehbg"

USAGE="$PROGRAM_NAME [center|fill|max|scale|tile] [path...]"

setting_re="\(center\|fill\|max\|scale\|tile\)"

is_setting () {
	printf "%s\n" "$1" | grep -xq "$setting_re"
}

set_setting () {
	sed "s;--bg-$setting_re;--bg-$1;"
}

set_args () {
	sed "s; \+'.*'$; $@;"
}

if [ -x $HOME/.fehbg ]
then
	if [ $# -gt 0 ]
	then
		script=$(cat $HOME/.fehbg | sed -n 's/^feh \+//p' | tail -n1)

		# change the script background mode setting
		if is_setting "$1"
		then
			script=$(echo $script | set_setting "$1")
			shift
		fi

		# change the script image files
		if [ $# -gt 0 ]
		then
			script=$(echo $script | set_args \
				"$(for f in "$@"; do printf " \'%s\'" "$f"; done)"
			)
		fi

		eval "feh $FEH_OPTIONS $script"
	else
		$HOME/.fehbg
	fi

	exit $?
fi

if [ $# -lt 1 ]
then
	set -- $(recent -n1 $DOWNLOADS)
fi

feh $FEH_OPTIONS --bg-${setting:-center} $@

