#!/bin/sh

read i j << EOF
$( mpc outputs | awk '
	/enabled$/ {i = NR}

	END {
		if (!i) {
			i = 0
			j = 1
		} else if (i == NR) {
			j = 1
		} else {
			j = i + 1
		}
		print i, j
	}'
)
EOF

if [ $i -ne 0 ]
then
	mpc disable $i 2>&1 > /dev/null
fi

mpc enable $j 2>&1 > /dev/null

mpc outputs

