#!/bin/sh

# tracks2cue [options]
#
# Utility to convert track lists to cue sheets
#
# Track lists are read from stdin with fields seperated by a tab character in
# the form:
#
#	TRACK	TITLE	LENGTH
#
# Where TRACK is a number, TITLE is any string and LENGTH is minutes and seconds
# seperated by a colon, for eg.
#
#	1	Song name	3:02
#
# Specifying the first track called "Song name" that is 3 minutes 2 seconds long.
# Which for eg. will output to stdin:
#
# 	...
# 	TRACK 01 AUDIO
# 	  TITLE "Cool song"
# 	  ...
# 	  INDEX 01 03:02:00
#
# TODO:
# 	* support frames (track ms * 75)
#
# OPTIONS
# 	-p [PERFORMER]
# 		Specify the performer of the recording
#
# 	-t [TITLE]
# 		Specify the title of the recording
#
# 	-f [FILE]
# 		Specify the file the cue sheet shall be based on
#
# ENVIRONMENT
# 	PERFORMER, TITLE and FILE may be present in the environment to specify
# 	those values in place of options.
#

while getopts "p:t:f:" opt
do
	case "$opt" in
		p)
			PERFORMER="$OPTARG"
			;;
		t)
			TITLE="$OPTARG"
			;;
		f)
			FILE="$OPTARG"
			;;
	esac
done

echo "PERFORMER \"$PERFORMER\""
echo "TITLE \"$TITLE\""
echo "FILE \"$FILE\" WAVE"

m_offset=0
s_offset=0

while read line
do
	track=$(echo "$line" | cut -f1)
	title=$(echo "$line" | cut -f2)
	length=$(echo "$line" | cut -f3)

	printf "  TRACK %02d AUDIO\n" $track
	echo   "    TITLE \"$title\""
	echo   "    PERFORMER \"$PERFORMER\""
	printf "    INDEX 01 %02d:%02d:00\n" $m_offset $s_offset

	m_delta=$(echo $length | cut -d':' -f1)
	s_delta=$(echo $length | cut -d':' -f2)

	s_offset=$((s_offset + s_delta))
	m_offset=$((m_offset + m_delta + $(echo "$s_offset / 60" | bc)))
	s_offset="$(echo "$s_offset % 60" | bc)"
done
