#!/bin/sh

# Transcode audio files without reducing the bitrate

PREFIX="${PREFIX:-./}"
EXT="${EXT:-mp3}"

# change file extension:
sext () {
	sed '/\./ s/.[^.]\+$/.'"$1"'/'
}

# ensure there is a slash after the input name
slash () {
	sed '/[^\/]$/ s/\(.\)$/\1\//'
}

# extract the bitrate
bitrate () {
	ffprobe -v quiet -print_format flat -show_entries format=bit_rate -i "$1" | \
		sed 's:format.bit_rate="\([^"]\+\)":\1:'
}

_transcode () {

	if [ ! -e "$1" ]
	then
		echo "error: '$1' does not exist" >&2
		return 1
	fi

	dest="$PREFIX"$(basename $(echo "$1" | sext "$EXT"))

	if [ -e "$dest" ]
	then
		echo "error: destination '$dest' already exists, skipping" >&2
		return 1
	fi

	rate="$(bitrate "$1")"

	if [ -z "$rate" ]
	then
		echo "error: failed to get bitrate from '$1'" >&2
		return 1
	fi

	ffmpeg -strict -2 -i "$1" -b:a "$rate" "$dest"
}

while getopts p:e: opt
do
	case $opt in
	p)
		PREFIX=$(echo $OPTARG | slash);;
	e)
		EXT="$OPTARG";;
	?)
		printf "Usage: %s: [-p prefix] [-e extension] [files...]\n" $0
		exit 2;;

	esac
done

shift $(($OPTIND - 1))

(
	IFS='
'
	for src in $@
	do
		if [ "$src" = "--" ]
		then
			while read src
			do
				_transcode "$src"
			done
			break
		else
			_transcode "$src"
		fi
	done
)


